version: "3.5"
services:
  nginx:
    volumes:
      - appdata:/var/www/html
    environment:
      NGINX_PUBLIC: /pub
      NGINX_TEMPLATE: magento2.conf
    depends_on:
      - php-fpm

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    image: docker.io/wardenenv/php-fpm:${PHP_VERSION:-7.4}${WARDEN_SVC_PHP_VARIANT:-}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - appdata:/var/www/html
    extra_hosts:
      - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - magento-init

  db:
    image: ${MAGENTO_REPOSITORY:-davidalger/magento}:${MAGENTO_VERSION}-mariadb${MAGENTO_VARIANT:-}
    command:
      - mysqld
      - --max_allowed_packet=1024M
      - --explicit_defaults_for_timestamp=on

  magento-init:
    image: ${MAGENTO_REPOSITORY:-davidalger/magento}:${MAGENTO_VERSION}${MAGENTO_VARIANT:-}
    volumes:
      - appdata:/var/www/html
    command: ["chown", "-R", "1000:1000", "/var/www/html"]

volumes:
  appdata: {}
