version: "3.5"
services:
  ## override volumes to eliminate bind mounts
  nginx:
    volumes:
      - appdata:/var/www/html
      - appmedia:/var/www/html/pub/media

  ## override volumes to eliminate bind mounts; depend on init container to ensure start order
  php-fpm:
    volumes:
      - rootcert:/etc/ssl/warden-rootca-cert
      - composer:/home/www-data/.composer
      - appdata:/var/www/html
      - appmedia:/var/www/html/pub/media
    depends_on:
      - magento-init

  ## override volumes to eliminate bind mounts; depend on init container to ensure start order
  php-debug:
    volumes:
      - rootcert:/etc/ssl/warden-rootca-cert
      - composer:/home/www-data/.composer
      - appdata:/var/www/html
      - appmedia:/var/www/html/pub/media
    depends_on:
      - magento-init

  ## change database image to one with pre-built sql artifact for import on container start
  db:
    image: ${MAGENTO_REPOSITORY:-davidalger/magento}:${MAGENTO_VERSION:-2.3}-mariadb${MAGENTO_VARIANT:-}

  ## functions as an init-container copying artifact files onto appdata volume then exits
  magento-init:
    image: ${MAGENTO_REPOSITORY:-davidalger/magento}:${MAGENTO_VERSION:-2.3}${MAGENTO_VARIANT:-}
    volumes:
      - appdata:/var/www/html
      - appmedia:/var/www/html/pub/media
    command: ["chown", "-R", "1000:1000", "/var/www/html"]

volumes:
  rootcert: {}
  composer: {}
  appdata: {}
  appmedia: {}
